name: Sign & Attach (Deprecated)

on:
  workflow_dispatch:
    inputs:
      note:
        description: 'Deprecated sign workflow. Use android-release.yml.'
        required: false

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deprecated: use .github/workflows/android-release.yml'
